/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HandlersRouteImport } from './routes/handlers'
import { Route as GeographyRouteImport } from './routes/geography'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DeposRouteImport } from './routes/depos'
import { Route as BulkOperationsRouteImport } from './routes/bulk-operations'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeographyBulkImportRouteImport } from './routes/geography_.bulk-import'
import { Route as EmployeesIdRouteImport } from './routes/employees_.$id'
import { Route as DeposBulkImportRouteImport } from './routes/depos_.bulk-import'
import { Route as DeposIdRouteImport } from './routes/depos_.$id'
import { Route as BrandsIdRouteImport } from './routes/brands_.$id'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HandlersRoute = HandlersRouteImport.update({
  id: '/handlers',
  path: '/handlers',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographyRoute = GeographyRouteImport.update({
  id: '/geography',
  path: '/geography',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DeposRoute = DeposRouteImport.update({
  id: '/depos',
  path: '/depos',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOperationsRoute = BulkOperationsRouteImport.update({
  id: '/bulk-operations',
  path: '/bulk-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographyBulkImportRoute = GeographyBulkImportRouteImport.update({
  id: '/geography_/bulk-import',
  path: '/geography/bulk-import',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees_/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeposBulkImportRoute = DeposBulkImportRouteImport.update({
  id: '/depos_/bulk-import',
  path: '/depos/bulk-import',
  getParentRoute: () => rootRouteImport,
} as any)
const DeposIdRoute = DeposIdRouteImport.update({
  id: '/depos_/$id',
  path: '/depos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIdRoute = BrandsIdRouteImport.update({
  id: '/brands_/$id',
  path: '/brands/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/brands': typeof BrandsRoute
  '/bulk-operations': typeof BulkOperationsRoute
  '/depos': typeof DeposRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/geography': typeof GeographyRoute
  '/handlers': typeof HandlersRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/visits': typeof VisitsRoute
  '/brands/$id': typeof BrandsIdRoute
  '/depos/$id': typeof DeposIdRoute
  '/depos/bulk-import': typeof DeposBulkImportRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/geography/bulk-import': typeof GeographyBulkImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/brands': typeof BrandsRoute
  '/bulk-operations': typeof BulkOperationsRoute
  '/depos': typeof DeposRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/geography': typeof GeographyRoute
  '/handlers': typeof HandlersRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/visits': typeof VisitsRoute
  '/brands/$id': typeof BrandsIdRoute
  '/depos/$id': typeof DeposIdRoute
  '/depos/bulk-import': typeof DeposBulkImportRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/geography/bulk-import': typeof GeographyBulkImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/brands': typeof BrandsRoute
  '/bulk-operations': typeof BulkOperationsRoute
  '/depos': typeof DeposRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/geography': typeof GeographyRoute
  '/handlers': typeof HandlersRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/visits': typeof VisitsRoute
  '/brands_/$id': typeof BrandsIdRoute
  '/depos_/$id': typeof DeposIdRoute
  '/depos_/bulk-import': typeof DeposBulkImportRoute
  '/employees_/$id': typeof EmployeesIdRoute
  '/geography_/bulk-import': typeof GeographyBulkImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/brands'
    | '/bulk-operations'
    | '/depos'
    | '/employees'
    | '/forgot-password'
    | '/geography'
    | '/handlers'
    | '/login'
    | '/notifications'
    | '/products'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/verify-email'
    | '/visits'
    | '/brands/$id'
    | '/depos/$id'
    | '/depos/bulk-import'
    | '/employees/$id'
    | '/geography/bulk-import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/brands'
    | '/bulk-operations'
    | '/depos'
    | '/employees'
    | '/forgot-password'
    | '/geography'
    | '/handlers'
    | '/login'
    | '/notifications'
    | '/products'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/verify-email'
    | '/visits'
    | '/brands/$id'
    | '/depos/$id'
    | '/depos/bulk-import'
    | '/employees/$id'
    | '/geography/bulk-import'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/brands'
    | '/bulk-operations'
    | '/depos'
    | '/employees'
    | '/forgot-password'
    | '/geography'
    | '/handlers'
    | '/login'
    | '/notifications'
    | '/products'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/verify-email'
    | '/visits'
    | '/brands_/$id'
    | '/depos_/$id'
    | '/depos_/bulk-import'
    | '/employees_/$id'
    | '/geography_/bulk-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandsRoute: typeof BrandsRoute
  BulkOperationsRoute: typeof BulkOperationsRoute
  DeposRoute: typeof DeposRoute
  EmployeesRoute: typeof EmployeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GeographyRoute: typeof GeographyRoute
  HandlersRoute: typeof HandlersRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VisitsRoute: typeof VisitsRoute
  BrandsIdRoute: typeof BrandsIdRoute
  DeposIdRoute: typeof DeposIdRoute
  DeposBulkImportRoute: typeof DeposBulkImportRoute
  EmployeesIdRoute: typeof EmployeesIdRoute
  GeographyBulkImportRoute: typeof GeographyBulkImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handlers': {
      id: '/handlers'
      path: '/handlers'
      fullPath: '/handlers'
      preLoaderRoute: typeof HandlersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geography': {
      id: '/geography'
      path: '/geography'
      fullPath: '/geography'
      preLoaderRoute: typeof GeographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depos': {
      id: '/depos'
      path: '/depos'
      fullPath: '/depos'
      preLoaderRoute: typeof DeposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-operations': {
      id: '/bulk-operations'
      path: '/bulk-operations'
      fullPath: '/bulk-operations'
      preLoaderRoute: typeof BulkOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geography_/bulk-import': {
      id: '/geography_/bulk-import'
      path: '/geography/bulk-import'
      fullPath: '/geography/bulk-import'
      preLoaderRoute: typeof GeographyBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees_/$id': {
      id: '/employees_/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depos_/bulk-import': {
      id: '/depos_/bulk-import'
      path: '/depos/bulk-import'
      fullPath: '/depos/bulk-import'
      preLoaderRoute: typeof DeposBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depos_/$id': {
      id: '/depos_/$id'
      path: '/depos/$id'
      fullPath: '/depos/$id'
      preLoaderRoute: typeof DeposIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands_/$id': {
      id: '/brands_/$id'
      path: '/brands/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof BrandsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandsRoute: BrandsRoute,
  BulkOperationsRoute: BulkOperationsRoute,
  DeposRoute: DeposRoute,
  EmployeesRoute: EmployeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GeographyRoute: GeographyRoute,
  HandlersRoute: HandlersRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VisitsRoute: VisitsRoute,
  BrandsIdRoute: BrandsIdRoute,
  DeposIdRoute: DeposIdRoute,
  DeposBulkImportRoute: DeposBulkImportRoute,
  EmployeesIdRoute: EmployeesIdRoute,
  GeographyBulkImportRoute: GeographyBulkImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
